# Numpy Basics

In [19]:
import numpy as np

In [20]:
# 1D array
np1 = np.array([1, 2, 5, 7])

# Range
np2 = np.arange(10)

# Step
np3 = np.arange(0, 10, 2)

# Zeros
np4 = np.zeros(10)

# Multidimensional zeros
np5 = np.zeros((2, 5))

# Full
np6 = np.full((10), 6)

# Multidimensional full
np7 = np.full((2, 5), 6)

print(np1, np2, np3)
print(np4, np5)
print(np6, np7)

[1 2 5 7] [0 1 2 3 4 5 6 7 8 9] [0 2 4 6 8]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[6 6 6 6 6 6 6 6 6 6] [[6 6 6 6 6]
 [6 6 6 6 6]]


In [21]:
# 1D array
a = np.array([0,1,2,3,4,5,6,7,8,9])
b = np.array([[1,2,3,4,5], [6,7,8,9,0], [10,11,12,13,14]])

## Slicing

In [22]:
# Slicing numpy arrays

# Return 3,4,5
print(a[2:5])

# Return from 4 till end
print(a[4:])

# Return negative slices eg: 7,8
print(a[-3: -1])

# Steps
print(a[1:5:2])

# Steps on the entire array
print(a[::2])


[2 3 4]
[4 5 6 7 8 9]
[7 8]
[1 3]
[0 2 4 6 8]


In [23]:
# Slice 2-D array

print(b[0:2, 1:3]) # a[row, col]

[[2 3]
 [7 8]]


## Functions

In [24]:
# Universal Function

print(np.exp(a))    # exponents, log, sin, cos
print(np.max(a))    # max/min
print(np.sign(a))   # 1 for +ve & 0 for -ve


[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
9
[0 1 1 1 1 1 1 1 1 1]


## Get Shape, Reshape, Flatten

In [25]:
# Get shape
print(a.shape) # 1D
print(b.shape) # 2D

# Reshape 1D to 2D
c = a.reshape(2,5)
print(c)

# Flatten 2D to 1D
d = b.reshape(-1)
print(d)

(10,)
(3, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 1  2  3  4  5  6  7  8  9  0 10 11 12 13 14]


In [26]:
# 3D Array
np3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

# Loop through each item of array
for x in np.nditer(np3):
    print(x, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

## Sort

In [27]:
a1 = np.array([7,2,8,3,5,3,2,9,1])
b1 = np.array(['John', 'Simon', 'Josh', 'Harry'])
c1 = np.array([True, False, False, True])

print(np.sort(a1))
print(np.sort(b1))
print(np.sort(c1))

# 2D
a2 = np.array([[5,7,1,9], [8,3,5,0]])
print(np.sort(a2)) # Sorts each row seperately

[1 2 2 3 3 5 7 8 9]
['Harry' 'John' 'Josh' 'Simon']
[False False  True  True]
[[1 5 7 9]
 [0 3 5 8]]


## Search & Filter

In [28]:
# Search
# np.where() returns tuple eg: (array[3,5], dtype=int64)
x = np.where(a1 == 3)
print(x[0])

# Return even items
y = np.where(a % 2 == 0)
print(y[0])

[3 5]
[0 2 4 6 8]


In [29]:
# Filter even items
filtered = a % 2 == 1   # Odd
print(filtered)
print(a, a[filtered])

[False  True False  True False  True False  True False  True]
[0 1 2 3 4 5 6 7 8 9] [1 3 5 7 9]
